### ISSUE TITLE
new function to normalize DataFrame

### ISSUE THREAD

**Issue by cjprybol** [oheil/NormalizeQuantiles.jl#1]
Hi @oheil,

Thanks for writing this awesome package. I'm using it starting with DataFrames, and would like to contribute a helper function that takes a DataFrame and an array of columns to normalize, and then returns a copy of the original DataFrame with the target columns quantile normalized

``` julia
myDF = DataFrame(Genes = ["A", "B", "C", "D", "E"], 
                    cond1 = rand(5),
                    cond2 = rand(5),
                    cond3 = rand(5))
```

should return something like

|  | Genes | cond1 | cond2 | cond3 |
| --- | --- | --- | --- | --- |
| 1 | A | 0.32563181788519513 | 0.21438356281559678 | 0.8771217378138845 |
| 2 | B | 0.6870295079889066 | 0.6915367387396687 | 0.7535393139297728 |
| 3 | C | 0.2862851833941058 | 0.16805347512816704 | 0.8187249261058329 |
| 4 | D | 0.4158104577567945 | 0.24391342294094476 | 0.829337861985237 |
| 5 | E | 0.3787968401059918 | 0.4015742563211182 | 0.30126103627947454 |

```
# quantile normalize columns with expression data
function MynormalizeQuantiles(data::DataFrames.DataFrame, dataColumns::Array{Symbol,1})
    # get columns to NOT normalize
    otherCols = []
    for col in names(data)
        if !in(col, dataCols)
            push!(otherCols, col)
        end
    end

    # save this subset of the dataframe for later
    forLater = data[Array{Symbol,1}(otherCols)]

    # convert columns of interest to DataArray
    data_DA = DataArray(data[:, dataColumns])

    # melt into 1x(nrow*ncol) array with `for i in data_DA`
    # if NA ? return null : else return converted Float
    data_NA = [isna(i) ? Nullable{Float64}() : Nullable{Float64}(i) for i in data_DA]

    # convert back to original nrow x ncol shape and quantileNormalize
    quantNorm = normalizeQuantiles(reshape(data_NA, size(data_DA)))

    # convert back to DataArray
    quantNorm_DA = reshape(DataArray([isnull(i) ? NA : get(i) for i in quantNorm]), size(quantNorm))

    # build new dataframe by appending columns in order
    newData = DataFrame()
    for i in 1:length(dataColumns)
        newData = hcat(newData, DataFrame(Dict(dataColumns[i] => quantNorm_DA[:, i])))
    end

    # merge and order back to original
    newData = hcat(newData, forLater)[names(data)]

    return newData
end

# normalize myDF on all but :Genes column
MynormalizeQuantiles(myDF, deleteat!(names(myDF), 1))
```

should return something like

|  | Genes | cond1 | cond2 | cond3 |
| --- | --- | --- | --- | --- |
| 1 | A | 0.43118489821018824 | 0.43118489821018824 | 0.7518959948474867 |
| 2 | B | 0.7518959948474867 | 0.7518959948474867 | 0.43118489821018824 |
| 3 | C | 0.2518665649339158 | 0.2518665649339158 | 0.4804783963842565 |
| 4 | D | 0.5489075253543833 | 0.4804783963842565 | 0.5489075253543833 |
| 5 | E | 0.4804783963842565 | 0.5489075253543833 | 0.2518665649339158 |

I tried to add this and submit a pull request myself using the instructions [here, under **Executive summary**](http://docs.julialang.org/en/release-0.4/manual/packages/#making-changes-to-an-existing-package), but after adding this function (and changing the name of the above function to `normalizeQuantiles`, rather than my temporary name `MynormalizeQuantiles`) the tests failed. I've never worked with Julia packages and had no idea where to start troubleshooting that, but would be happy to retry a pull request if you could give me some pointers, or if it's easier, feel free to add it to the code base yourself.

I would also be interested in working on auto detection and usage of multiple cores, using your examples [here](https://github.com/oheil/NormalizeQuantiles.jl#multicore-usage-examples-for-julia-version--04). For example, detect the number of cores available with `nprocs()`, and if more than 2 are available, automatically use the SharedArray methodology.

**Comment by oheil** [comment]
Hi Cameron,

this is a great enhancement of the package. I am currently on vacation with limited internet access. I will check on weekend when I am back. Thanks for your contribution.

Regards,

Oli

**Comment by oheil** [comment]
Hi Cameron,

I won't add the helper function to the package, because I want to have the package free from any dependencies to other packages. Thats why I have removed the dependency to the DataArray package when moving from julia 0.3 to 0.4.
Julia is still very young and I don't want to have to much trouble with future versions when the code base is changing. Dependencies to other packages introduce even more problems e.g. when you have to wait for new versions of other packages before you can change your own code to reflect changes at the base.
(In future, when julia 0.3 gets really old I will remove the old DataArray code which is still in the source).

A second reason for not adding this helper function is that the current implementation is highly optimized for performance and for low memory consumption. Adding wrappers for other data types may result im bad performance for the introduced data type e.g. when I have to convert the types in the wrapper funtion. People will complain here and I have to say its not me its the other package, which always sounds lame.

Anyways this is how I would do your normalization with Dataframes:

```
using DataFrames
using NormalizeQuantiles

df = DataFrame(Genes = ["A", "B", "C", "D", "E"],Symbols = ["S1", "S2", "S3", "S4", "S5"],cond1 = rand(5),cond2 = rand(5),cond3 = rand(5))

df[2,:cond1] = NA
df[3,:cond3] = NA

#getting the indices of the data columns
di = [ find(y->y==x,names(df))[1] for x in [:cond1,:cond2,:cond3] ]

da = DataArray(df[di])

arrayWithNA = convert(Array{Nullable{Float64}},reshape([isna(da[i])?Nullable{Float64}():Nullable{Float64}(da[i]) for i=1:length(da)],size(da)))
qn = normalizeQuantiles(arrayWithNA)
daqn = DataArray(Float64,size(qn))
daqn[1:length(qn)] = DataArray(reshape([isnull(qn[i])?NA:get(qn[i]) for i=1:length(qn)],size(qn)))[1:length(qn)]

#creating the new DataFrame
dfqn=df
for index in di
    dfqn[:,index]=daqn[:,index-di[1]+1]
end
```

So far to the helper function.

If your tests are failing I can look into the output/error log and I will help you to find the problem. I assume that you don't have
`using DataFrames`
in your package. As you have typed this in your console everything works but the test envirnoment does not run this command implicitly.

The problem with nproc() is that it is not a detection of the hardware but it just gives you back what you added with addproc().
Currently (julia 0.4) addproc() seems also to be buggy. Try the following code in a new console:

```
addprocs()
using NormalizeQuantiles
la=randn((10000,1000));
tf=Array{Nullable{Float64}}(la);
normalizeQuantiles(tf);
@time normalizeQuantiles(tf);
sa=SharedArray(Nullable{Float64},(size(tf,1),size(tf,2)));
sa[:]=tf[:];
normalizeQuantiles(sa);
@time normalizeQuantiles(sa);
```

Everything should be find. But if you change the order of the first two commands and run it again:

```
using NormalizeQuantiles
addprocs()
la=randn((10000,1000));
tf=Array{Nullable{Float64}}(la);
normalizeQuantiles(tf);
@time normalizeQuantiles(tf);
sa=SharedArray(Nullable{Float64},(size(tf,1),size(tf,2)));
sa[:]=tf[:];
normalizeQuantiles(sa);
@time normalizeQuantiles(sa);
```

You will get a lot of error messages. (I have checked in julia 0.4.1).
So I think its still to early for to much automatisms here.

Oli

**Comment by cjprybol** [comment]
Hi Oli,

Thanks for the explanation. Those are all great points, and I understand the reasoning behind all of them. I made no attempt to focus on performance, and just went for a clear and simple implementation, so given the errors/breaks that can arise as things continue to change during Julia development and your focus on keeping the package highly performant, I don't disagree with your decision. If anyone else has a similar use case to mine, this issue can serve as a reference for them to implement the functionality on their own.

I noticed you tagged this with enhancement and help wanted. I plan to use this package more in the future, so if you'd like any help with enhancements or maintenance in general, I'd be interested in contributing.

My concerns have been addressed, so feel free to close this if you wish!

best,
Cameron

**Comment by oheil** [comment]
Removed "help wanted"  :-)
I close this thread, but for future reference I note:
Maybe it is a good idea to create a wrapper package e.g. "NormalizeQuantileWrappers" which contain all needed wrapper function to the core normalization routines. Or at least those wrappers which introduce dependencies to other packages (like DataArrays, DataFrames, and whatever there to come).
